import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { WORKSPACE } from "./config.js";
import { ProjectMemoryStore, memoryContext } from "./project-memory.js";
import { RuntimeStore } from "./store.js";
import { runAiCodeTask, type CodeTaskRequest } from "./code-orchestrator.js";
import { runProductionWebAgent } from "./web-production-agent.js";
import type { ProductionWebTaskRequest } from "./web-production.js";

export interface WorkflowStep { id:string; agent:string; task:string; depends_on?:string[]; max_iterations?:number; }
export interface WorkflowDefinition { name:string; description?:string; steps:WorkflowStep[]; file:string; }
export interface AgentDefinition { name:string; description:string; kind:"code"|"web"|"math"|"generic"; tools:string[]; max_iterations:number; prompt:string; file:string; }
export interface Skill { name:string; description?:string; body:string; file:string; }
export interface McpServer { name:string; url?:string; command?:string; args?:string[]; enabled:boolean; tools:string[]; }
const ROOT=path.resolve(WORKSPACE),BDS=path.join(ROOT,".better-deepseek"),AGENTS=path.join(BDS,"agents"),WORKFLOWS=path.join(BDS,"workflows"),SKILLS=path.join(BDS,"skills");
async function ensure(){await Promise.all([fs.mkdir(AGENTS,{recursive:true}),fs.mkdir(WORKFLOWS,{recursive:true}),fs.mkdir(SKILLS,{recursive:true})]);}
function frontmatter(text:string){const m=text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);const meta:Record<string,string>={};if(m)for(const l of m[1].split(/\r?\n/)){const i=l.indexOf(":");if(i>0)meta[l.slice(0,i).trim()]=l.slice(i+1).trim();}return{meta,body:m?.[2]??text};}
export async function loadAgents(){await ensure();const out:AgentDefinition[]=[];for(const f of (await fs.readdir(AGENTS)).filter(x=>x.endsWith(".md"))){const p=frontmatter(await fs.readFile(path.join(AGENTS,f),"utf8"));out.push({name:p.meta.name??path.basename(f,".md"),description:p.meta.description??"",kind:(p.meta.kind as AgentDefinition["kind"])??"generic",tools:(p.meta.tools??"").split(",").map(x=>x.trim()).filter(Boolean),max_iterations:Math.max(1,Math.min(30,Number(p.meta.max_iterations??10))),prompt:p.body,file:path.join(AGENTS,f)});}return out;}
export async function loadSkills(){await ensure();const out:Skill[]=[];for(const d of await fs.readdir(SKILLS)){const f=path.join(SKILLS,d,"SKILL.md");try{const p=frontmatter(await fs.readFile(f,"utf8"));out.push({name:p.meta.name??d,description:p.meta.description,body:p.body,file:f});}catch{}}return out;}
export async function loadWorkflows(){await ensure();const out:WorkflowDefinition[]=[];for(const f of (await fs.readdir(WORKFLOWS)).filter(x=>x.endsWith(".md"))){const file=path.join(WORKFLOWS,f),p=frontmatter(await fs.readFile(file,"utf8"));const steps=p.body.split(/\r?\n/).flatMap((l,i)=>{const m=l.match(/^\s*-\s*agent\s*=\s*([^;]+);\s*task\s*=\s*(.+)$/);return m?[{id:`step_${i+1}`,agent:m[1].trim(),task:m[2].trim()}]:[];});out.push({name:p.meta.name??path.basename(f,".md"),description:p.meta.description,steps,file});}return out;}
export async function writeAgent(d:Omit<AgentDefinition,"file">){await ensure();const f=path.join(AGENTS,`${d.name.replace(/[^\w.-]/g,"_")}.md`);await fs.writeFile(f,`---\nname: ${d.name}\ndescription: ${d.description}\nkind: ${d.kind}\ntools: ${d.tools.join(",")}\nmax_iterations: ${d.max_iterations}\n---\n${d.prompt}\n`,{mode:0o600});return f;}
export async function writeWorkflow(d:Omit<WorkflowDefinition,"file">){await ensure();const f=path.join(WORKFLOWS,`${d.name.replace(/[^\w.-]/g,"_")}.md`);await fs.writeFile(f,`---\nname: ${d.name}\ndescription: ${d.description??""}\n---\n${d.steps.map(s=>`- agent = ${s.agent}; task = ${s.task}`).join("\n")}\n`,{mode:0o600});return f;}
export class McpRegistry {private readonly servers=new Map<string,McpServer>();add(s:McpServer){if(!/^[\w.-]{1,64}$/.test(s.name))throw new Error("invalid MCP server name");if(s.url&&!/^https?:\/\//.test(s.url))throw new Error("MCP URL must be HTTP(S)");const v={...s,enabled:s.enabled!==false,tools:s.tools??[]};this.servers.set(s.name,v);return v;}remove(n:string){return this.servers.delete(n);}list(){return [...this.servers.values()];}enable(n:string,v:boolean){const s=this.servers.get(n);if(!s)throw new Error("MCP server not found");s.enabled=v;return s;}}
export interface OrchestrationEvent{type:string;payload:Record<string,unknown>}
export class Orchestrator {private readonly controls=new Map<string,{cancelled:boolean}>();constructor(private readonly memory:ProjectMemoryStore,private readonly runtime:RuntimeStore){}cancel(id:string){const c=this.controls.get(id);if(!c)return false;c.cancelled=true;return true;}
async run(projectId:string,steps:WorkflowStep[],emit:(e:OrchestrationEvent)=>void){const runId=`run_${crypto.randomUUID().replaceAll("-","").slice(0,16)}`;this.controls.set(runId,{cancelled:false});const results:Record<string,unknown>={};try{for(const step of steps){if(this.controls.get(runId)?.cancelled)throw new Error("workflow cancelled");for(const d of step.depends_on??[])if(!(d in results))throw new Error(`workflow dependency missing: ${d}`);const mem=this.memory.search(projectId,step.task,20);emit({type:"step_started",payload:{run_id:runId,step_id:step.id,agent:step.agent,memory_hits:mem.length}});let result:unknown;if(step.agent.startsWith("code")){const r:CodeTaskRequest={task:`${memoryContext(mem)}\n${step.task}`,max_iterations:step.max_iterations??10};result=await runAiCodeTask(r,this.runtime,e=>emit({type:"code_event",payload:{run_id:runId,step_id:step.id,event:e}}));}else if(step.agent.startsWith("web")){const r:ProductionWebTaskRequest={goal:`${memoryContext(mem)}\n${step.task}`,max_pages:10,max_depth:2,time_budget_minutes:5,interaction_level:"read-only"};result=await runProductionWebAgent(r,this.runtime,e=>emit({type:"web_event",payload:{run_id:runId,step_id:step.id,event:e}}));}else result={status:"delegated",agent:step.agent,task:step.task};results[step.id]=result;this.memory.write(projectId,{module:step.agent.startsWith("math")?"math":step.agent.startsWith("web")?"web":"code",type:"decision",key:`workflow.${runId}.${step.id}`,value:JSON.stringify(result).slice(0,20000),confidence:1,source:`workflow:${runId}`});emit({type:"step_completed",payload:{run_id:runId,step_id:step.id,result}});}return{run_id:runId,status:"completed",results};}finally{this.controls.delete(runId);}}
}
