import http from "node:http";
import { WebSocketServer, type WebSocket } from "ws";
import { authenticateBearer } from "./auth.js";
import { HOST, PORT, TOKEN, WORKSPACE } from "./config.js";
import { ProjectMemoryStore } from "./project-memory.js";
import { RuntimeStore } from "./store.js";
import { loadAgents, loadSkills, loadWorkflows, McpRegistry, Orchestrator, type WorkflowDefinition } from "./agent-orchestration-v2.js";
import { loadAgentConfig, permitted } from "./agent-config.js";

const CONTROL_PORT=Number(process.env.BDS_CONTROL_PORT??PORT+2);const memory=new ProjectMemoryStore();const runtime=new RuntimeStore();const orchestrator=new Orchestrator(memory,runtime);const mcp=new McpRegistry();
function json(res:http.ServerResponse,status:number,value:unknown){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(JSON.stringify(value));}
async function body(req:http.IncomingMessage){const chunks:Buffer[]=[];let n=0;return await new Promise<string>((resolve,reject)=>{req.on("data",(c:Buffer)=>{n+=c.length;if(n>2_000_000){reject(new Error("request body too large"));req.destroy();return;}chunks.push(c)});req.on("end",()=>resolve(Buffer.concat(chunks).toString("utf8")));req.on("error",reject)});}
function auth(req:http.IncomingMessage){return authenticateBearer(req.headers.authorization,TOKEN);}
export function createAgentControlServer(){const server=http.createServer(async(req,res)=>{if(req.url==="/control/health"){json(res,200,{ok:true,service:"agent-control",host:HOST,port:CONTROL_PORT});return;}if(!auth(req)){json(res,401,{ok:false,error:"unauthorized"});return;}try{const cfg=await loadAgentConfig();if(req.method==="GET"&&req.url==="/memory/projects"){json(res,200,{ok:true,projects:memory.listProjects()});return;}if(req.method==="POST"&&req.url==="/memory/projects"){const b=JSON.parse(await body(req));if(typeof b.name!=="string")throw new Error("name is required");json(res,201,{ok:true,project:memory.createProject(b.name,typeof b.workspace_path==="string"?b.workspace_path:WORKSPACE)});return;}const pm=req.url?.match(/^\/memory\/projects\/([^/]+)\/memories$/);if(pm&&req.method==="GET"){json(res,200,{ok:true,memories:memory.list(decodeURIComponent(pm[1]))});return;}if(pm&&req.method==="POST"){const b=JSON.parse(await body(req));json(res,201,{ok:true,result:memory.write(decodeURIComponent(pm[1]),{module:b.module,type:b.type,key:b.key,value:b.value,confidence:b.confidence,source:b.source})});return;}const ps=req.url?.match(/^\/memory\/projects\/([^/]+)\/memories\/search$/);if(ps&&req.method==="GET"){const q=new URL(req.url,"http://localhost").searchParams.get("q")??"";json(res,200,{ok:true,results:memory.search(decodeURIComponent(ps[1]),q,Number(new URL(req.url,"http://localhost").searchParams.get("max_results")??20))});return;}const pd=req.url?.match(/^\/memory\/projects\/([^/]+)\/memories\/([^/]+)$/);if(pd&&req.method==="DELETE"){json(res,200,{ok:memory.delete(decodeURIComponent(pd[1]),decodeURIComponent(pd[2]))});return;}const proj=req.url?.match(/^\/memory\/projects\/([^/]+)$/);if(proj&&req.method==="DELETE"){memory.deleteProject(decodeURIComponent(proj[1]));json(res,200,{ok:true});return;}
if(req.method==="GET"&&req.url==="/agents"){json(res,200,{ok:true,agents:await loadAgents(),skills:await loadSkills(),workflows:await loadWorkflows(),mcp:mcp.list(),permissions:cfg.permissions});return;}if(req.method==="POST"&&req.url==="/mcp"){const b=JSON.parse(await body(req));if(b.action==="remove"){json(res,200,{ok:mcp.remove(String(b.server))});return;}if(b.action==="enable"){json(res,200,{ok:true,server:mcp.enable(String(b.server),Boolean(b.enabled))});return;}if(b.action==="add"){const s=mcp.add({name:String(b.server),url:b.url,command:b.command,args:Array.isArray(b.args)?b.args:undefined,enabled:b.enabled!==false,tools:Array.isArray(b.tools)?b.tools:[]});json(res,201,{ok:true,server:s});return;}throw new Error("unsupported MCP action");}
if(req.method==="POST"&&req.url==="/workflows/run"){const b=JSON.parse(await body(req));if(typeof b.project!=="string"||!Array.isArray(b.steps))throw new Error("project and steps are required");const stepList=b.steps as any[];for(const s of stepList){if(!permitted(cfg.permissions,`agent.${String(s.agent)}`))throw new Error(`agent ${String(s.agent)} is denied by permission policy`);}const events:any[]=[];const result=await orchestrator.run(b.project,stepList,e=>events.push(e));json(res,200,{ok:true,result,events});return;}if(req.method==="POST"&&req.url?.match(/^\/workflows\/[^/]+\/cancel$/)){const id=decodeURIComponent(req.url.slice("/workflows/".length,-"/cancel".length));json(res,200,{ok:orchestrator.cancel(id)});return;}if(req.method==="GET"&&req.url==="/config"){json(res,200,{ok:true,workspace:WORKSPACE,config:cfg,mcp:mcp.list()});return;}json(res,404,{ok:false,error:"not_found"});}catch(error){json(res,400,{ok:false,error:error instanceof Error?error.message:String(error)});}});
const wss=new WebSocketServer({noServer:true,maxPayload:1_000_000});const clients=new Set<WebSocket>();wss.on("connection",socket=>{clients.add(socket);socket.on("message",async data=>{try{const m=JSON.parse(data.toString());if(m.type==="auth"){if(m.token!==TOKEN){socket.close(1008,"invalid token");return;}socket.send(JSON.stringify({type:"control/status",payload:{ok:true}}));return;}if(m.type==="workflow/run"){const events=(e:unknown)=>socket.send(JSON.stringify({type:"workflow/event",payload:e}));const result=await orchestrator.run(String(m.payload.project),m.payload.steps,events);socket.send(JSON.stringify({type:"workflow/result",payload:result}));return;}socket.send(JSON.stringify({type:"control/error",payload:{message:"unsupported message"}}));}catch(e){socket.send(JSON.stringify({type:"control/error",payload:{message:e instanceof Error?e.message:String(e)}}));}});socket.on("close",()=>clients.delete(socket));});server.on("upgrade",(req,socket,head)=>{const u=new URL(req.url??"/",`http://${HOST}`);if(u.pathname!=="/control/ws"){socket.destroy();return;}wss.handleUpgrade(req,socket,head,ws=>wss.emit("connection",ws,req));});server.on("close",()=>{wss.close();for(const c of clients)c.close();memory.close();runtime.close();});return server;}
