import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { WORKSPACE } from "./config.js";
import { ProjectMemoryStore, memoryContext } from "./project-memory.js";
import { runAiCodeTask, type CodeTaskRequest } from "./code-orchestrator.js";
import { runProductionWebAgent } from "./web-production-agent.js";
import type { ProductionWebTaskRequest } from "./web-production.js";

export type AgentKind="code"|"web"|"math"|"generic";
export interface AgentDefinition { name:string; description:string; kind:AgentKind; tools:string[]; max_iterations:number; prompt:string; file:string; }
export interface WorkflowStep { id:string; agent:string; task:string; depends_on?:string[]; max_iterations?:number; }
export interface WorkflowDefinition { name:string; description?:string; steps:WorkflowStep[]; file:string; }
export interface Skill { name:string; description?:string; body:string; file:string; }
export interface McpServer { name:string; url?:string; command?:string; args?:string[]; enabled:boolean; tools:string[]; }

const ROOT=path.resolve(WORKSPACE);const BDS=path.join(ROOT,".better-deepseek");const AGENTS=path.join(BDS,"agents");const WORKFLOWS=path.join(BDS,"workflows");const SKILLS=path.join(BDS,"skills");
async function files(dir:string,ext:string){try{return(await fs.readdir(dir)).filter(x=>x.endsWith(ext)).sort();}catch{return[];}}
function parseFrontmatter(text:string){const m=text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);if(!m)return {meta:{} as Record<string,string>,body:text};const meta:Record<string,string>={};for(const line of m[1].split(/\r?\n/)){const i=line.indexOf(":");if(i>0)meta[line.slice(0,i).trim()]=line.slice(i+1).trim().replace(/^['"]|['"]$/g,"");}return{meta,body:m[2]};}
export async function ensureAgentDirs(){await Promise.all([fs.mkdir(AGENTS,{recursive:true}),fs.mkdir(WORKFLOWS,{recursive:true}),fs.mkdir(SKILLS,{recursive:true})]);}
export async function loadAgents():Promise<AgentDefinition[]>{await ensureAgentDirs();const out:AgentDefinition[]=[];for(const file of await files(AGENTS,".md")){const full=path.join(AGENTS,file);const parsed=parseFrontmatter(await fs.readFile(full,"utf8"));out.push({name:parsed.meta.name??path.basename(file,".md"),description:parsed.meta.description??"",kind:(parsed.meta.kind as AgentKind)??"generic",tools:(parsed.meta.tools??"").split(",").map(x=>x.trim()).filter(Boolean),max_iterations:Math.max(1,Math.min(30,Number(parsed.meta.max_iterations??10))),prompt:parsed.body,file:full});}return out;}
export async function loadSkills():Promise<Skill[]>{await ensureAgentDirs();const out:Skill[]=[];for(const name of await fs.readdir(SKILLS).catch(()=>[])){const full=path.join(SKILLS,name,"SKILL.md");try{const parsed=parseFrontmatter(await fs.readFile(full,"utf8"));out.push({name:parsed.meta.name??name,description:parsed.meta.description,body:parsed.body,file:full});}catch{}}return out;}
export async function loadWorkflows():Promise<WorkflowDefinition[]>{await ensureAgentDirs();const out:WorkflowDefinition[]=[];for(const file of await files(WORKFLOWS,".md")){const full=path.join(WORKFLOWS,file);const parsed=parseFrontmatter(await fs.readFile(full,"utf8"));const steps:WorkflowStep[]=[];for(const line of parsed.body.split(/\r?\n/)){const m=line.match(/^\s*-\s*agent\s*=\s*([^;]+);\s*task\s*=\s*(.+)$/);if(m)steps.push({id:`step_${steps.length+1}`,agent:m[1].trim(),task:m[2].trim()});}out.push({name:parsed.meta.name??path.basename(file,".md"),description:parsed.meta.description,steps,file:full});}return out;}
export async function writeAgent(def:Omit<AgentDefinition,"file">){await ensureAgentDirs();const safe=def.name.replace(/[^a-zA-Z0-9_-]/g,"_");const file=path.join(AGENTS,`${safe}.md`);await fs.writeFile(file,`---\nname: ${def.name}\ndescription: ${def.description}\nkind: ${def.kind}\ntools: ${def.tools.join(",")}\nmax_iterations: ${def.max_iterations}\n---\n${def.prompt}\n`,{mode:0o600});return file;}
export async function writeWorkflow(def:Omit<WorkflowDefinition,"file">){await ensureAgentDirs();const safe=def.name.replace(/[^a-zA-Z0-9_-]/g,"_");const file=path.join(WORKFLOWS,`${safe}.md`);const body=def.steps.map(s=>`- agent = ${s.agent}; task = ${s.task}`).join("\n");await fs.writeFile(file,`---\nname: ${def.name}\ndescription: ${def.description??""}\n---\n${body}\n`,{mode:0o600});return file;}
export class McpRegistry { private servers=new Map<string,McpServer>(); add(server:McpServer){if(!/^[a-zA-Z0-9._-]{1,64}$/.test(server.name))throw new Error("invalid MCP server name");if(server.url&&!/^https?:\/\//.test(server.url))throw new Error("MCP URL must be HTTP(S)");this.servers.set(server.name,{...server,enabled:server.enabled!==false,tools:server.tools??[]});return this.servers.get(server.name)!;} remove(name:string){return this.servers.delete(name);} list(){return [...this.servers.values()];} enable(name:string,enabled:boolean){const s=this.servers.get(name);if(!s)throw new Error("MCP server not found");s.enabled=enabled;return s;} }
export interface OrchestrationEvent { type:string; payload:Record<string,unknown>; }
export class Orchestrator { private controls=new Map<string,{cancelled:boolean}>(); constructor(private readonly memory:ProjectMemoryStore){} cancel(id:string){const c=this.controls.get(id);if(!c)return false;c.cancelled=true;return true;}
  async run(projectId:string,steps:WorkflowStep[],emit:(e:OrchestrationEvent)=>void){const runId=`run_${crypto.randomUUID().replaceAll("-","").slice(0,16)}`;this.controls.set(runId,{cancelled:false});const results:Record<string,unknown>={};try{for(const step of steps){const c=this.controls.get(runId);if(c?.cancelled)throw new Error("workflow cancelled");for(const dep of step.depends_on??[])if(!(dep in results))throw new Error(`workflow dependency missing: ${dep}`);const memories=this.memory.search(projectId,step.task,20);emit({type:"step_started",payload:{run_id:runId,step_id:step.id,agent:step.agent,memory_hits:memories.length}});let result:unknown;if(step.agent.startsWith("code")){const req:CodeTaskRequest={task:`${memoryContext(memories)}\n${step.task}`,max_iterations:step.max_iterations??10};result=await runAiCodeTask(req, this.memory as never,(event)=>emit({type:"code_event",payload:{run_id:runId,step_id:step.id,event}}));}else if(step.agent.startsWith("web")){const req:ProductionWebTaskRequest={goal:`${memoryContext(memories)}\n${step.task}`,max_pages:10,max_depth:2,time_budget_minutes:5,interaction_level:"read-only"};result=await runProductionWebAgent(req,this.memory as never,(event)=>emit({type:"web_event",payload:{run_id:runId,step_id:step.id,event}}));}else{result={status:"delegated",agent:step.agent,task:step.task};}results[step.id]=result;this.memory.write(projectId,{module:step.agent.startsWith("math")?"math":step.agent.startsWith("web")?"web":"code",type:"decision",key:`workflow.${runId}.${step.id}`,value:JSON.stringify(result).slice(0,20000),confidence:1,source:`workflow:${runId}`});emit({type:"step_completed",payload:{run_id:runId,step_id:step.id,result}});}return{run_id:runId,status:"completed",results};}finally{this.controls.delete(runId);}}
}
