import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
import { WORKSPACE } from "./config.js";
import type { RuntimeStore } from "./store.js";

export type CodeRisk="low"|"medium"|"high"|"critical";
export interface CodeTaskRequest{task:string;workspace?:string;max_iterations?:number;approval?:"auto_for_known"|"always";tools?:string[];task_id?:string;}
export interface CodeApproval{id:string;task_id:string;tool:string;risk:CodeRisk;command?:string[];files?:string[];expires_at:string;status:"pending"|"approved"|"denied";}
const SECRET_NAMES=new Set([".env",".env.local",".env.production",".env.development",".ssh","id_rsa","id_ed25519","credentials.json"]);
const SHELL_EXECUTABLES=new Set(["git","lake","zig","cargo","python3","python","pytest","coqc","isabelle","sage","node","npm","npx"]);
const COMMANDS:Readonly<Record<string,readonly string[]>>=Object.freeze({"git.status":["git","status","--short"],"git.diff":["git","diff","--no-ext-diff","--unified=3"],"git.log":["git","log","-5","--oneline"],"lean4.check":["lake","env","lean"],"lean4.build":["lake","build"],"coq.check":["coqc"],"isabelle.build":["isabelle","build"],"sage.run":["sage"],"rust.check":["cargo","check"],"rust.test":["cargo","test"],"zig.build":["zig","build"],"python.test":["python3","-m","pytest"]});
function resolveWorkspace(candidate?:string){const base=path.resolve(candidate??WORKSPACE);const root=path.resolve(WORKSPACE);if(base!==root&&!base.startsWith(`${root}${path.sep}`))throw new Error("workspace is outside configured runtime workspace");return base;}
function resolveFile(workspace:string,file:string){if(path.isAbsolute(file))throw new Error("absolute file paths are not accepted");const target=path.resolve(workspace,file);if(target!==workspace&&!target.startsWith(`${workspace}${path.sep}`))throw new Error("file escapes workspace");if(SECRET_NAMES.has(path.basename(target))||SECRET_NAMES.has(path.basename(path.dirname(target))))throw new Error("secret-like files are denied by default");return target;}
export function riskFor(tool:string):CodeRisk{if(["git.commit","fs.delete","package.install","shell.external"].includes(tool))return"high";if(["fs.edit","fs.write","shell.run","git.add","compiler.run"].includes(tool))return"medium";return"low";}
function run(command:readonly string[],cwd:string,timeoutMs:number):Promise<{stdout:string;stderr:string;code:number|null;timed_out:boolean;truncated:boolean}>{return new Promise((resolve,reject)=>{const child=spawn(command[0],command.slice(1),{cwd,shell:false,stdio:["ignore","pipe","pipe"],detached:process.platform!=="win32",windowsHide:true});let stdout="",stderr="",bytes=0,truncated=false,settled=false;const append=(which:"stdout"|"stderr",chunk:Buffer)=>{const remain=1024*1024-bytes;if(remain<=0){truncated=true;return;}const text=chunk.subarray(0,remain).toString("utf8");bytes+=Buffer.byteLength(text);if(which==="stdout")stdout+=text;else stderr+=text;if(chunk.length>remain)truncated=true;};const kill=()=>{try{process.kill(-child.pid!,"SIGKILL");}catch{try{child.kill("SIGKILL");}catch{}}};const timer=setTimeout(()=>{if(settled)return;settled=true;kill();resolve({stdout,stderr,code:null,timed_out:true,truncated});},timeoutMs);child.stdout.on("data",c=>append("stdout",c));child.stderr.on("data",c=>append("stderr",c));child.once("error",e=>{if(settled)return;settled=true;clearTimeout(timer);reject(e);});child.once("close",code=>{if(settled)return;settled=true;clearTimeout(timer);resolve({stdout,stderr,code,timed_out:false,truncated});});});}
export function listTools(){return[["fs.read","low"],["fs.write","medium"],["fs.edit","medium"],["fs.list","low"],["fs.search","low"],["fs.delete","high"],["shell.run","medium"],["git.status","low"],["git.diff","low"],["git.commit","high"],["compiler.run","medium"],["lsp.diagnostics","low"],["memory.write","low"]].map(([name,risk])=>({name,risk:risk as CodeRisk}));}
export async function readFile(workspace:string,file:string){return fs.readFile(resolveFile(workspace,file),"utf8");}
export async function listDir(workspace:string,dir="."){return(await fs.readdir(resolveFile(workspace,dir),{withFileTypes:true})).map(e=>`${e.isDirectory()?"d":"f"} ${e.name}`).sort();}
export async function searchCode(workspace:string,pattern:string){if(!pattern||pattern.length>200)throw new Error("invalid search pattern");const rx=new RegExp(pattern,"i"),out:string[]=[];async function walk(dir:string){for(const e of await fs.readdir(dir,{withFileTypes:true})){if(SECRET_NAMES.has(e.name)||e.name==="node_modules"||e.name===".git")continue;const p=path.join(dir,e.name);if(e.isDirectory())await walk(p);else{try{const t=await fs.readFile(p,"utf8");if(rx.test(t))out.push(path.relative(workspace,p));if(out.length>=500)return;}catch{}}}}await walk(workspace);return out;}
export async function writeFile(workspace:string,file:string,content:string){const target=resolveFile(workspace,file);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,content,{encoding:"utf8",mode:0o600});}
export async function editFile(workspace:string,file:string,search:string,replacement:string){const target=resolveFile(workspace,file);const before=await fs.readFile(target,"utf8");const count=before.split(search).length-1;if(count!==1)throw new Error(`edit target must match exactly once; found ${count}`);await fs.writeFile(target,before.replace(search,replacement),"utf8");}
export async function deleteFile(workspace:string,file:string){await fs.rm(resolveFile(workspace,file),{force:true});}
export async function runTool(taskId:string,tool:string,args:Record<string,unknown>,workspace:string,store:RuntimeStore):Promise<unknown>{const domain=tool.split(".")[0];if(!new Set(["fs","shell","git","lean4","isabelle","coq","sage","lsp","memory"]).has(domain))throw new Error("tool domain is not allowed");const risk=riskFor(tool);store.audit("code.tool.start",{task_id:taskId,tool,risk});if(tool==="fs.read")return{content:await readFile(workspace,String(args.file))};if(tool==="fs.list")return{entries:await listDir(workspace,String(args.dir??"."))};if(tool==="fs.search")return{files:await searchCode(workspace,String(args.pattern))};if(tool==="fs.write"){await writeFile(workspace,String(args.file),String(args.content??""));return{ok:true};}if(tool==="fs.edit"){await editFile(workspace,String(args.file),String(args.search),String(args.replacement));return{ok:true};}if(tool==="fs.delete")throw new Error("fs.delete requires explicit approval");if(tool.startsWith("git.")){if(tool==="git.commit")throw new Error("git.commit requires explicit approval");const cmd=COMMANDS[tool];if(!cmd)throw new Error("git command is not allowlisted");return run(cmd,workspace,15000);}if(tool==="shell.run"){if(!Array.isArray(args.argv)||!args.argv.every(x=>typeof x==="string"))throw new Error("shell.run requires argv:string[]");const argv=args.argv as string[];if(!argv[0]||!SHELL_EXECUTABLES.has(path.basename(argv[0])))throw new Error("executable is not allowlisted");return run(argv,workspace,120000);}if(tool==="compiler.run"){const command=COMMANDS[`${String(args.language)}.${String(args.action??"check")}`];if(!command)throw new Error("compiler command is not allowlisted");return run(args.file?[...command,String(args.file)]:[...command],workspace,120000);}if(tool==="lsp.diagnostics")return{diagnostics:[]};if(tool==="memory.write"){store.writeCodeMemory(workspace,String(args.key),String(args.value??""));return{ok:true};}throw new Error(`unsupported code tool: ${tool}`);}
export async function executeApprovedAction(tool:string,args:Record<string,unknown>,workspace:string){if(tool==="fs.delete"){await deleteFile(workspace,String(args.file));return{ok:true};}if(tool==="git.commit"){const message=String(args.message??"").trim();if(!message)throw new Error("commit message is required");return run(["git","commit","-m",message],workspace,15000);}throw new Error("approval does not authorize this tool");}
export {resolveWorkspace};
