import http from "node:http";
import { WebSocketServer } from "ws";
import { authenticateBearer } from "./auth.js";
import { HOST, PORT, TOKEN, LIMITS, WORKSPACE } from "./config.js";
import { RuntimeStore } from "./store.js";
import { runTool, listTools, executeApprovedAction, type CodeTaskRequest } from "./code-production.js";
import { runAiCodeTask, pauseAiCodeTask, resumeAiCodeTask, cancelAiCodeTask } from "./code-orchestrator.js";

const CODE_PORT=Number(process.env.BDS_CODE_PORT??PORT+1);const store=new RuntimeStore();const activeTasks=new Set<Promise<unknown>>();
function json(res:http.ServerResponse,status:number,value:unknown){const text=JSON.stringify(value);res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(text);}
function body(req:http.IncomingMessage){return new Promise<string>((resolve,reject)=>{let total=0;const chunks:Buffer[]=[];req.on("data",c=>{total+=c.length;if(total>LIMITS.httpBodyBytes){reject(new Error("request body too large"));req.destroy();return;}chunks.push(c)});req.on("end",()=>resolve(Buffer.concat(chunks).toString("utf8")));req.on("error",reject);});}
function authed(req:http.IncomingMessage){return authenticateBearer(req.headers.authorization,TOKEN);}
function parseJson(text:string){try{return JSON.parse(text) as any;}catch{throw new Error("invalid JSON");}}
function startTask(request:CodeTaskRequest,send:(event:unknown)=>void){if(activeTasks.size>=LIMITS.maxConcurrentJobs)throw new Error("maximum concurrent background jobs reached");const taskId=request.task_id??`code-${Date.now()}-${Math.random().toString(16).slice(2,10)}`;const task=runAiCodeTask({...request,task_id:taskId},store,send);activeTasks.add(task);task.finally(()=>activeTasks.delete(task));return taskId;}

export function createCodeServer(){
  const server=http.createServer(async(req,res)=>{
    if(req.url==="/code/health"){json(res,200,{ok:true,service:"better-deepseek-code-agent",host:HOST,port:CODE_PORT});return;}
    if(!authed(req)){json(res,401,{ok:false,error:"unauthorized"});return;}
    try{
      if(req.method==="GET"&&req.url==="/code/health"){json(res,200,{ok:true,workspace:WORKSPACE,tools:listTools(),active_tasks:activeTasks.size});return;}
      if(req.method==="GET"&&req.url==="/code/workspace"){json(res,200,{ok:true,workspace:WORKSPACE,memory:store.listCodeMemory(WORKSPACE)});return;}
      if(req.method==="POST"&&req.url==="/code/workspace/index"){const pattern=typeof req.headers["x-index-pattern"]==="string"?req.headers["x-index-pattern"]:"[A-Za-z]";const result=await runTool(`index-${Date.now()}`,"fs.search",{pattern},WORKSPACE,store);json(res,200,{ok:true,result});return;}
      if(req.method==="GET"&&req.url?.match(/^\/code\/tasks\/[^/]+$/)){const id=decodeURIComponent(req.url.slice("/code/tasks/".length));const task=store.getCodeTask(id);json(res,task?200:404,task?{ok:true,task}:{ok:false,error:"task_not_found"});return;}
      if(req.method==="POST"&&req.url==="/code/tasks"){const request=parseJson(await body(req)) as CodeTaskRequest;const taskId=startTask(request,event=>broadcast({type:"code/event",payload:event}));json(res,202,{ok:true,task_id:taskId,status:"queued"});return;}
      if(req.method==="POST"&&req.url?.match(/^\/code\/tasks\/[^/]+\/pause$/)){const id=decodeURIComponent(req.url.slice("/code/tasks/".length,-"/pause".length));const changed=pauseAiCodeTask(id);json(res,changed?200:404,changed?{ok:true,task_id:id,status:"paused"}:{ok:false,error:"task_not_running"});return;}
      if(req.method==="POST"&&req.url?.match(/^\/code\/tasks\/[^/]+\/resume$/)){const id=decodeURIComponent(req.url.slice("/code/tasks/".length,-"/resume".length));const changed=resumeAiCodeTask(id);json(res,changed?200:404,changed?{ok:true,task_id:id,status:"resumed"}:{ok:false,error:"task_not_running"});return;}
      if(req.method==="POST"&&req.url?.match(/^\/code\/tasks\/[^/]+\/cancel$/)){const id=decodeURIComponent(req.url.slice("/code/tasks/".length,-"/cancel".length));const changed=cancelAiCodeTask(id);json(res,changed?200:404,changed?{ok:true,task_id:id,status:"cancelled"}:{ok:false,error:"task_not_running"});return;}
      if(req.method==="POST"&&req.url?.match(/^\/code\/tools\/[^/]+$/)){const tool=decodeURIComponent(req.url.slice("/code/tools/".length));const args=parseJson(await body(req));const risk=listTools().find(t=>t.name===tool)?.risk;if(!risk)throw new Error("tool is not allowlisted");if(risk==="high"){const id=`code-approval-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;store.createApproval(id,String(args.task_id??"manual"),tool,JSON.stringify({source:"manual",workspace:WORKSPACE,args}),new Date(Date.now()+300000).toISOString());json(res,202,{ok:true,approval_required:true,approval_id:id,tool,risk});return;}const result=await runTool(`manual-${Date.now()}`,tool,args,WORKSPACE,store);json(res,200,{ok:true,result});return;}
      if(req.method==="POST"&&req.url?.match(/^\/code\/approvals\/[^/]+$/)){const id=decodeURIComponent(req.url.slice("/code/approvals/".length));const decision=parseJson(await body(req)).decision;if(decision!=="approved"&&decision!=="denied")throw new Error("decision must be approved or denied");const approval=store.getApproval(id);if(!approval){json(res,404,{ok:false,error:"approval_not_found"});return;}if(Date.parse(approval.expires_at)<=Date.now()){store.decideApproval(id,"denied");json(res,410,{ok:false,error:"approval_expired"});return;}if(!store.decideApproval(id,decision)){json(res,409,{ok:false,error:"approval_already_decided"});return;}if(decision==="denied"){json(res,200,{ok:true,id,decision});return;}const target=JSON.parse(approval.target);if(target.source==="orchestrator"){json(res,200,{ok:true,id,decision,continued:true});return;}const result=await executeApprovedAction(approval.action,target.args,WORKSPACE);json(res,200,{ok:true,id,decision,result});return;}
      if(req.method==="GET"&&req.url==="/code/memory"){json(res,200,{ok:true,memory:store.listCodeMemory(WORKSPACE)});return;}
      json(res,404,{ok:false,error:"not_found"});
    }catch(error){json(res,400,{ok:false,error:error instanceof Error?error.message:String(error)});}
  });
  const wss=new WebSocketServer({noServer:true,maxPayload:LIMITS.wsMessageBytes});const clients=new Set<any>();function broadcast(event:unknown){const text=JSON.stringify(event);for(const c of clients)if(c.readyState===1)c.send(text);}
  wss.on("connection",socket=>{clients.add(socket);socket.on("message",async data=>{try{const message=JSON.parse(data.toString()) as {type?:string;token?:string;payload?:any};if(message.type==="auth"){if(message.token!==TOKEN){socket.close(1008,"invalid token");return;}socket.send(JSON.stringify({type:"code/status",payload:{ok:true,workspace:WORKSPACE,tools:listTools()}}));return;}if(message.type==="code/task"){startTask(message.payload as CodeTaskRequest,event=>socket.send(JSON.stringify({type:"code/event",payload:event})));return;}if(message.type==="code/pause"){if(!pauseAiCodeTask(String(message.payload?.task_id??"")))throw new Error("task not running");return;}if(message.type==="code/resume"){if(!resumeAiCodeTask(String(message.payload?.task_id??"")))throw new Error("task not paused");return;}if(message.type==="code/cancel"){if(!cancelAiCodeTask(String(message.payload?.task_id??"")))throw new Error("task not running");return;}if(message.type==="code/tool"){const p=message.payload as {tool:string;args:Record<string,unknown>};const risk=listTools().find(t=>t.name===p.tool)?.risk;if(!risk)throw new Error("tool is not allowlisted");if(risk==="high"){const id=`code-approval-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;store.createApproval(id,String(p.args.task_id??"manual"),p.tool,JSON.stringify({source:"manual",workspace:WORKSPACE,args:p.args}),new Date(Date.now()+300000).toISOString());socket.send(JSON.stringify({type:"code/event",payload:{type:"approval_required",approval_id:id,tool:p.tool,risk}}));return;}const result=await runTool(`ws-${Date.now()}`,p.tool,p.args,WORKSPACE,store);socket.send(JSON.stringify({type:"code/tool_result",payload:{tool:p.tool,result}}));return;}socket.send(JSON.stringify({type:"code/error",payload:{message:"unsupported message"}}));}catch(error){socket.send(JSON.stringify({type:"code/error",payload:{message:error instanceof Error?error.message:String(error)}}));}});socket.on("close",()=>clients.delete(socket));});
  server.on("upgrade",(req,socket,head)=>{const url=new URL(req.url??"/",`http://${HOST}`);if(url.pathname!=="/code/ws"){socket.destroy();return;}wss.handleUpgrade(req,socket,head,ws=>wss.emit("connection",ws,req));});
  server.on("close",()=>{wss.close();for(const c of clients)c.close();store.close();});return server;
}
