import crypto from "node:crypto";
import { chromium, type Browser, type BrowserContext } from "playwright";
import type { RuntimeStore } from "./store.js";

export type InteractionLevel = "read-only" | "click" | "fill-forms";
export type TaskStatus = "queued" | "running" | "paused" | "completed" | "cancelled" | "failed";
export interface ProductionWebTaskRequest { goal: string; start_url?: string; max_pages?: number; max_depth?: number; time_budget_minutes?: number; interaction_level?: InteractionLevel; session_name?: string; allowed_domains?: string[]; blocked_domains?: string[]; resume_task_id?: string; }
export interface ApprovalRequest { id: string; task_id: string; action: "fill-form" | "submit-form" | "click-high-risk"; target: string; expires_at: string; status: "pending" | "approved" | "denied" | "expired"; }
interface Control { paused: boolean; cancelled: boolean; waiters: Array<() => void>; }
const controls = new Map<string, Control>();
const loginContexts = new Map<string, { browser: Browser; context: BrowserContext; expiresAt: string }>();
const MAX_SESSION_AGE_MS = 30 * 24 * 60 * 60 * 1000;
function secretKey(): Buffer { const material = process.env.BDS_SESSION_KEY || process.env.BDS_RUNTIME_TOKEN || ""; if (!material) throw new Error("BDS_SESSION_KEY or BDS_RUNTIME_TOKEN is required for encrypted sessions"); return crypto.createHash("sha256").update(material).digest(); }
function encrypt(value: string): string { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", secretKey(), iv); const ciphertext = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return Buffer.concat([iv, cipher.getAuthTag(), ciphertext]).toString("base64url"); }
function decrypt(value: string): string { const raw = Buffer.from(value, "base64url"); const decipher = crypto.createDecipheriv("aes-256-gcm", secretKey(), raw.subarray(0, 12)); decipher.setAuthTag(raw.subarray(12, 28)); return Buffer.concat([decipher.update(raw.subarray(28)), decipher.final()]).toString("utf8"); }
function normalizeDomains(values: unknown): string[] { if (!Array.isArray(values)) return []; return [...new Set(values.filter((x): x is string => typeof x === "string").map((x) => x.trim().toLowerCase()).filter(Boolean))].slice(0, 100); }
export function normalizeProductionRequest(request: ProductionWebTaskRequest) { if (!request || typeof request.goal !== "string" || !request.goal.trim()) throw new Error("goal is required"); const maxPages = Number.isFinite(request.max_pages) ? Math.floor(request.max_pages!) : 25; const maxDepth = Number.isFinite(request.max_depth) ? Math.floor(request.max_depth!) : 3; const timeBudget = Number.isFinite(request.time_budget_minutes) ? Math.floor(request.time_budget_minutes!) : 20; const interaction = request.interaction_level ?? "read-only"; if (!["read-only", "click", "fill-forms"].includes(interaction)) throw new Error("invalid interaction level"); return { goal: request.goal.trim(), start_url: request.start_url, max_pages: Math.max(1, Math.min(25, maxPages)), max_depth: Math.max(0, Math.min(3, maxDepth)), time_budget_minutes: Math.max(1, Math.min(20, timeBudget)), interaction_level: interaction, session_name: request.session_name, allowed_domains: normalizeDomains(request.allowed_domains), blocked_domains: normalizeDomains(request.blocked_domains), resume_task_id: request.resume_task_id }; }
export function domainAllowed(hostname: string, allowed: string[], blocked: string[]): boolean { const host = hostname.toLowerCase(); if (blocked.some((d) => host === d || host.endsWith(`.${d}`))) return false; if (!allowed.length) return true; return allowed.some((d) => host === d || host.endsWith(`.${d}`)); }
export function createControl(taskId: string): Control { const c = { paused: false, cancelled: false, waiters: [] as Array<() => void> }; controls.set(taskId, c); return c; }
export function getControl(taskId: string): Control | undefined { return controls.get(taskId); }
export function pauseTask(taskId: string): boolean { const c = controls.get(taskId); if (!c) return false; c.paused = true; return true; }
export function resumeTask(taskId: string): boolean { const c = controls.get(taskId); if (!c) return false; c.paused = false; for (const r of c.waiters.splice(0)) r(); return true; }
export function cancelTask(taskId: string): boolean { const c = controls.get(taskId); if (!c) return false; c.cancelled = true; c.paused = false; for (const r of c.waiters.splice(0)) r(); return true; }
export async function waitForResume(taskId: string): Promise<void> { const c = controls.get(taskId); if (!c || !c.paused) return; await new Promise<void>((resolve) => c.waiters.push(resolve)); }
export function clearControl(taskId: string): void { controls.delete(taskId); }
export async function createLoginSession(name: string): Promise<{ id: string; name: string; expires_at: string }> { if (!/^[A-Za-z0-9._-]{1,64}$/.test(name)) throw new Error("invalid session name"); if (loginContexts.has(name)) throw new Error("session already open"); const browser = await chromium.launch({ headless: false }); const context = await browser.newContext(); const expiresAt = new Date(Date.now() + MAX_SESSION_AGE_MS).toISOString(); loginContexts.set(name, { browser, context, expiresAt }); return { id: name, name, expires_at: expiresAt }; }
export async function saveLoginSession(name: string, store: RuntimeStore): Promise<void> { const current = loginContexts.get(name); if (!current) throw new Error("session is not open"); const state = await current.context.storageState(); store.upsertWebSession(name, encrypt(JSON.stringify(state)), current.expiresAt); await current.context.close(); await current.browser.close(); loginContexts.delete(name); store.audit("web.session.saved", { name }); }
export async function deleteSession(name: string, store: RuntimeStore): Promise<boolean> { const current = loginContexts.get(name); if (current) { await current.context.close().catch(() => undefined); await current.browser.close().catch(() => undefined); loginContexts.delete(name); } const removed = store.deleteWebSession(name); if (removed) store.audit("web.session.deleted", { name }); return removed; }
export function listStoredSessions(store: RuntimeStore): Array<{ id: string; name: string; expires_at: string }> { return store.listWebSessions().map((s) => ({ id: s.name, name: s.name, expires_at: s.expires_at })); }
export async function loadSessionContext(store: RuntimeStore, name: string): Promise<BrowserContext> { const stored = store.getWebSession(name); if (!stored) throw new Error("session not found"); if (Date.parse(stored.expires_at) <= Date.now()) throw new Error("session expired"); const state = JSON.parse(decrypt(stored.state_ciphertext)); return chromium.launch({ headless: true }).then(async (browser) => { const context = await browser.newContext({ storageState: state }); (context as BrowserContext & { __bdsBrowser?: Browser }).__bdsBrowser = browser; return context; }); }
export async function closeLoadedContext(context: BrowserContext): Promise<void> { const browser = (context as BrowserContext & { __bdsBrowser?: Browser }).__bdsBrowser; await context.close(); await browser?.close().catch(() => undefined); }
