const DEFAULT_RUNTIME = { http: "http://127.0.0.1:3037", ws: "ws://127.0.0.1:3037/ws", codeWs: "ws://127.0.0.1:3038/code/ws", controlHttp: "http://127.0.0.1:3039", controlWs: "ws://127.0.0.1:3039/control/ws" };
let state = { connected: false, lastError: null, runtime: DEFAULT_RUNTIME };
const sockets = new Map();
async function settings(){const v=await chrome.storage.local.get({token:"",runtime:DEFAULT_RUNTIME});state.runtime={...DEFAULT_RUNTIME,...(v.runtime||{})};return v;}
function closeSockets(){for(const ws of sockets.values()){try{ws.close();}catch{}}sockets.clear();}
async function connect(kind,url,message,tabId){const existing=sockets.get(kind);if(existing?.readyState===WebSocket.OPEN){existing.send(JSON.stringify(message));return;}const {token}=await settings();if(!token||token.length<32)throw new Error("Runtime token is not configured");const ws=new WebSocket(url);sockets.set(kind,ws);await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{try{ws.close();}catch{}reject(new Error(`${kind} runtime connection timeout`));},5000);ws.addEventListener("open",()=>{clearTimeout(timer);ws.send(JSON.stringify({type:"auth",token}));ws.addEventListener("message",e=>{try{const event=JSON.parse(e.data);if(tabId)chrome.tabs.sendMessage(tabId,{type:"runtime/event",event}).catch(()=>{});}catch{state.lastError="invalid runtime message";}},{once:false});resolve();},{once:true});ws.addEventListener("error",()=>{clearTimeout(timer);reject(new Error(`${kind} runtime connection failed`));},{once:true});});state.connected=true;state.lastError=null;chrome.runtime.sendMessage({type:"runtime/status",state}).catch(()=>{});ws.send(JSON.stringify(message));}
async function runtimeFetch(path,init={}){const {token}=await settings();if(!token||token.length<32)throw new Error("Runtime token is not configured");const headers=new Headers(init.headers||{});headers.set("Authorization",`Bearer ${token}`);headers.set("Cache-Control","no-store");const response=await fetch(`${state.runtime.http}${path}`,{...init,headers});const text=await response.text();let body;try{body=JSON.parse(text);}catch{body={raw:text};}if(!response.ok)throw new Error(body.error||`Runtime HTTP ${response.status}`);return body;}
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{(async()=>{try{if(message?.type==="runtime/config"){await settings();sendResponse({ok:true,runtime:state.runtime});return;}if(message?.type==="runtime/status"){sendResponse({ok:true,state});return;}if(message?.type==="runtime/fetch"){sendResponse({ok:true,body:await runtimeFetch(message.path,message.init||{})});return;}if(message?.type==="runtime/tag"){const tag=message.tag;const kind=tag?.name==="CODE_AGENT"?"code":tag?.name?.startsWith("MEMORY_")||tag?.name==="PROJECT_CONTEXT"||tag?.name==="WORKFLOW"||tag?.name==="AGENT_DEFINE"||tag?.name==="SUBAGENT"||tag?.name==="MCP_MANAGE"?"control":"runtime";const url=kind==="code"?state.runtime.codeWs:kind==="control"?state.runtime.controlWs:state.runtime.ws;const payload=kind==="code"?{type:"code/task",payload:tag.attributes||{}}:{type:"tags",payload:{tags:[tag],text:message.text||""}};await connect(kind,url,payload,sender.tab?.id);sendResponse({ok:true,queued:true});return;}sendResponse({ok:false,error:"unsupported message"});}catch(error){sendResponse({ok:false,error:error instanceof Error?error.message:String(error)});}})();return true;});
chrome.runtime.onStartup.addListener(()=>{closeSockets();settings().catch(()=>{});});chrome.runtime.onInstalled.addListener(()=>settings().catch(()=>{}));
